### ISSUE TITLE
There are no illustrations for downloaded chapters

### ISSUE THREAD

**Issue by VectorNEON** [LNReader/lnreader#1298]
### Steps to reproduce

When downloading a chapter from ranobelib (I didn’t check others, because I don’t use them, maybe there is a problem on others too), when opening the downloaded chapter there are no illustrations, the problem appeared on version r1016, while on r1015 the chapters download normally with illustrations.

Here is an example from DxD chapter 220
![изображение_2024-10-30_232603739](https://github.com/user-attachments/assets/d21fe22b-dec3-4ef0-bcb0-0a0d160a8af9)
![изображение_2024-10-30_232529567](https://github.com/user-attachments/assets/7f5b5d84-4de8-4552-b118-6b3893c34781)

### Expected behavior

Must swing illustrations

### Actual behavior

No illustrations

### LNReader version

2.0.0

### Android version

Android 10

### Device

Realme C11 (2020)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
@Rider21

**Comment by Rider21** [comment]
I found what the problem was
I think the react-native function [`URL`](https://github.com/LNReader/lnreader/blob/c498d7e9cd1dae69f1474a6bf372f16538225d53/src/services/download/downloadChapter.ts#L52) works differently, it adds an extra `/` to the end of the string always.
And that's why the source was responding with `500 error` when downloading.
![Screenshot_20241031-125355](https://github.com/user-attachments/assets/ad15b3ac-e3ef-48b8-b7b4-ce81f0b4a1a6)
![Screenshot_20241031-125255](https://github.com/user-attachments/assets/9e527ed8-ecad-461b-8cc1-29819c0a70f6)

**Comment by nyagami** [comment]
Yeah, URL in react native is a `handmade` module
[Detail issue](https://github.com/facebook/react-native/issues/24428)

![image](https://github.com/user-attachments/assets/f74efa0d-5354-4484-94d5-077f974368fd)

We should add [react-native-url-polyfill](https://www.npmjs.com/package/react-native-url-polyfill)
