### ISSUE TITLE
[Feature request] Backup restore resets the read progress.

### ISSUE THREAD

**Issue by VGFlash** [LNReader/lnreader#34]
Whenever an update comes I have to create a backup of the Library and restore after reinstalling the new updated apk, but whenever I restore I see that my reading progress is reset that is for eg if I have read till 50 chapters when I restore it will show 0 chapters read.

**Comment by joseph619** [comment]
Please mention the app version in the OP for bug reports!

**Comment by rajarsheechatterjee** [comment]
@VGFlash Right now the backup only contains the novel data, so while restoring, the chapters are fetched from the source and because of that the progress gets reset. I will be making improvements to the backups so that it also saves chapters and downloads.

@joseph619 I should create issue templates.

**Comment by VGFlash** [comment]
Sorry for not providing the version etc and I will edit it into feature request I guess
Version of app: Stable 1.0.21
Android 11
