### ISSUE TITLE
Exporting requires internet access

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#810]
### Steps to reproduce

1. turn off internet
2. export a novel

### Expected behavior

successful export

### Actual behavior

![IMG_20231014_203345](https://github.com/LNReader/lnreader/assets/75091899/25589f06-c0a1-4994-a83f-41a96b42c90c)

### LNReader version

1.1.18

### Android version

Android 8 miui 8

### Device

Huawei p8 lite 2017

### Other details

A dev said it should not ask internet access ( a must).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Exporting EPUBs would require internet access as the [images are downloaded](https://github.com/CD-Z/react-native-epub-creator/blob/master/src/main.ts#L243) in the process. 

Ideally the creation shouldn't fail due to it but that'd be an upstream issue in [react-native-epub-creator](https://github.com/CD-Z/react-native-epub-creator).
