### ISSUE TITLE
Plugin Beta

### ISSUE THREAD

**Issue by nyagami** [LNReader/lnreader#941]
1. Using the full path instead of the whole url.
   - eg: `https://website.abc.xyz.com/novels/abc-xyz.html` -> the full path is: `/noels/abc-xyz.html`
3. Paginated novel.   
   - fetchChapters:
       - `page` is `string` for flexible usage
       - If site has ascending order page: must return chapter list with ascending order by release time 
       - If site has only descending order page (the first page is the latest): must return chapter list with descending order by release time and the latest chapter.
       - custom `page` : `volume 1`, `special volume`, `artwork`
   - update the novel and its first page, then lazy update for the other pages.
   - Chapter Drawer only displays the page where the current chapter is in
   - novel filter/sort is applied only for page scope
 5. Should we support multiple lang?
    - Provide each plugin a storage and let it cook

**Comment by nyagami** [comment]
@rajarsheechatterjee again, should we implement pages for novel. fetching 10k paginated chapters at once is extremely painful

**Comment by K1ngfish3r** [comment]
For paginated novel you can probably have a
-refresh novel button (full)
-refresh starting from (pageNo) => delete all chapters which have >= pageNo and fetch starting from there.
So this way, even if some pages were cloud flare blocked, can resume from that page where it wasn't blocked rather than delete novel and start over.
(this doesn't work if chapters are sorted backwards)

**Comment by nyagami** [comment]
Also, this means in Beta, all current plugins will be turned into `broken` and they needed help from plugins contributors again :)

**Comment by nyagami** [comment]
1 done in https://github.com/LNReader/lnreader/pull/944
2 done in https://github.com/LNReader/lnreader/pull/947
